app:
  logMode: "Development" # Production
  ginRunMode: "debug" # "debug","release","test"
  version: "1.0.0"
  readTimeout: 60000000
  writeTimeout: 60000000
  endPointPort: 8080
  jwtSecret: "123"
  pageSize: 10
  objectCashTtl: 3600

database:
  host: "host.docker.internal"
  port: 5432

redis:
  host: "host.docker.internal:6379"
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200
