app:
  logMode: "Production" # Development
  ginRunMode: "release" # "debug","release","test"
  version: "1.0.0"
  readTimeout: 60000000
  writeTimeout: 60000000
  endPointPort: 8080
  jwtSecret: "123"
  pageSize: 10
  objectCashTtl: 3600

database:
  host: localhost
  port: 5432

redis:
  host: "127.0.0.1:6379"
  maxIdle: 30
  maxActive: 30
  idleTimeout: 200
